#include "util/zip/jxx.util.zip.ZipFile.h"
#include <algorithm>
#include <fstream>
#include <iterator>
#include "io/jxx.io.ByteArrayInputStream.h"
#include "io/jxx.io.File.h"
#include "lang/jxx.lang.NullPointerException.h"
#include "lang/jxx.lang.String.h"
#include "util/jxx.util.VectorEnumeration.h"
#include "util/zip/jxx.util.zip.ZipEntry.h"
#include "util/zip/jxx.util.zip.ZipException.h"
namespace jxx::util::zip {
ZipFile::ZipFile(const ::jxx::Ptr<::jxx::lang::String>&n){open_(n);} ZipFile::ZipFile(const ::jxx::Ptr<::jxx::io::File>&f){if(f==nullptr)throw ::jxx::lang::NullPointerException();open_(f->getPath());} ZipFile::~ZipFile(){try{close();}catch(...){}}
std::uint16_t ZipFile::u16_(std::size_t o)const{if(o+2>bytes_.size())throw ZipException("truncated zip");return static_cast<std::uint16_t>(bytes_[o]|(bytes_[o+1]<<8));} std::uint32_t ZipFile::u32_(std::size_t o)const{if(o+4>bytes_.size())throw ZipException("truncated zip");return static_cast<std::uint32_t>(u16_(o)|(static_cast<std::uint32_t>(u16_(o+2))<<16));}
void ZipFile::open_(const ::jxx::Ptr<::jxx::lang::String>&n){if(n==nullptr)throw ::jxx::lang::NullPointerException();name_=n;std::ifstream in(n->utf8(),std::ios::binary);if(!in)throw ZipException("zip file not found");bytes_.assign(std::istreambuf_iterator<char>(in),{});if(bytes_.size()<22)throw ZipException("invalid zip");std::size_t eocd=std::string::npos;const auto low=bytes_.size()>65557?bytes_.size()-65557:0;for(std::size_t p=bytes_.size()-22;;--p){if(u32_(p)==0x06054b50){eocd=p;break;}if(p==low)break;}if(eocd==std::string::npos)throw ZipException("end record not found");const auto count=u16_(eocd+10);const auto central=u32_(eocd+16);const auto commentLength=u16_(eocd+20);if(eocd+22+commentLength>bytes_.size())throw ZipException("invalid zip comment");if(commentLength)comment_=::jxx::NEW<::jxx::lang::String>(std::string(reinterpret_cast<const char*>(bytes_.data()+eocd+22),commentLength));std::size_t p=central;for(std::uint16_t i=0;i<count;++i){if(u32_(p)!=0x02014b50)throw ZipException("invalid central directory");const auto method=u16_(p+10);const auto crc=u32_(p+16);const auto compressed=u32_(p+20);const auto size=u32_(p+24);const auto nl=u16_(p+28);const auto xl=u16_(p+30);const auto cl=u16_(p+32);const auto local=u32_(p+42);if(p+46+nl+xl+cl>bytes_.size())throw ZipException("truncated central directory");auto e=::jxx::NEW<ZipEntry>(::jxx::NEW<::jxx::lang::String>(std::string(reinterpret_cast<const char*>(bytes_.data()+p+46),nl)));e->method_=method;e->crc_=crc;e->compressedSize_=compressed;e->size_=size;e->localOffset_=local;if(u32_(local)!=0x04034b50)throw ZipException("invalid local header");e->dataOffset_=static_cast<::jxx::lang::jlong>(local+30+u16_(local+26)+u16_(local+28));entries_.push_back(e);p+=46+nl+xl+cl;}}
void ZipFile::ensureOpen_()const{if(closed_)throw ZipException("zip file closed");}
::jxx::Ptr<ZipEntry> ZipFile::getEntry(const ::jxx::Ptr<::jxx::lang::String>&n)const{ensureOpen_();if(n==nullptr)throw ::jxx::lang::NullPointerException();for(const auto&e:entries_)if(e->getName()->equals(n))return ::jxx::NEW<ZipEntry>(e);return nullptr;}
::jxx::Ptr<::jxx::util::Enumeration<ZipEntry>> ZipFile::entries(){ensureOpen_();std::vector<::jxx::Ptr<ZipEntry>> copy;for(const auto&e:entries_)copy.push_back(::jxx::NEW<ZipEntry>(e));return ::jxx::NEW<::jxx::util::VectorEnumeration<ZipEntry>>(std::move(copy));}
::jxx::Ptr<::jxx::io::InputStream> ZipFile::getInputStream(const ::jxx::Ptr<ZipEntry>&e){ensureOpen_();if(e==nullptr)throw ::jxx::lang::NullPointerException();const auto original=getEntry(e->getName());if(original==nullptr)return nullptr;if(original->method_!=ZipEntry::STORED_)throw ZipException("compressed entries require DEFLATE backend");const auto start=static_cast<std::size_t>(original->dataOffset_);const auto n=static_cast<std::size_t>(original->size_);if(start+n>bytes_.size())throw ZipException("truncated entry");auto data=::jxx::NEW<::jxx::lang::ByteArrayType>(static_cast<::jxx::lang::jint>(n));for(std::size_t i=0;i<n;++i)(*data)[static_cast<::jxx::lang::jint>(i)]=static_cast<::jxx::lang::jbyte>(bytes_[start+i]);return ::jxx::CAST<::jxx::io::InputStream>(::jxx::NEW<::jxx::io::ByteArrayInputStream>(data));}
::jxx::Ptr<::jxx::lang::String> ZipFile::getName()const{return name_;} ::jxx::lang::jint ZipFile::size()const noexcept{return static_cast<::jxx::lang::jint>(entries_.size());} ::jxx::Ptr<::jxx::lang::String> ZipFile::getComment()const{return comment_;} void ZipFile::close(){if(closed_)return;closed_=true;bytes_.clear();entries_.clear();}
}
