#include "util/concurrent/locks/jxx.util.concurrent.locks.AbstractQueuedLongSynchronizer.h"
#include <chrono>
#include "lang/jxx.lang.Class.h"
#include "lang/jxx.lang.Exceptions.h"
namespace jxx::util::concurrent::locks {
::jxx::Ptr<::jxx::lang::ClassAny>AbstractQueuedLongSynchronizer::Class(){return JxxClassInfoMarker::Class();}AbstractQueuedLongSynchronizer::AbstractQueuedLongSynchronizer():Super(){}
::jxx::lang::jlong AbstractQueuedLongSynchronizer::getState()const noexcept{return state_.load(std::memory_order_acquire);}void AbstractQueuedLongSynchronizer::setState(::jxx::lang::jlong v)noexcept{state_.store(v,std::memory_order_release);}::jxx::lang::jbool AbstractQueuedLongSynchronizer::compareAndSetState(::jxx::lang::jlong e,::jxx::lang::jlong u)noexcept{return state_.compare_exchange_strong(e,u,std::memory_order_acq_rel);}
void AbstractQueuedLongSynchronizer::acquire(::jxx::lang::jlong a){if(!tryAcquire(a))queuedAcquire_(a,false);}void AbstractQueuedLongSynchronizer::acquireInterruptibly(::jxx::lang::jlong a){acquire(a);}::jxx::lang::jbool AbstractQueuedLongSynchronizer::tryAcquireNanos(::jxx::lang::jlong a,::jxx::lang::jlong n){return tryAcquire(a)||timedAcquire_(a,false,std::chrono::nanoseconds(n));}
::jxx::lang::jbool AbstractQueuedLongSynchronizer::release(::jxx::lang::jlong a){if(!tryRelease(a))return false;queueChanged_.notify_all();return true;}void AbstractQueuedLongSynchronizer::acquireShared(::jxx::lang::jlong a){if(tryAcquireShared(a)<0)queuedAcquire_(a,true);}void AbstractQueuedLongSynchronizer::acquireSharedInterruptibly(::jxx::lang::jlong a){acquireShared(a);}::jxx::lang::jbool AbstractQueuedLongSynchronizer::tryAcquireSharedNanos(::jxx::lang::jlong a,::jxx::lang::jlong n){return tryAcquireShared(a)>=0||timedAcquire_(a,true,std::chrono::nanoseconds(n));}::jxx::lang::jbool AbstractQueuedLongSynchronizer::releaseShared(::jxx::lang::jlong a){if(!tryReleaseShared(a))return false;queueChanged_.notify_all();return true;}
void AbstractQueuedLongSynchronizer::queuedAcquire_(::jxx::lang::jlong a,bool s){auto t=::jxx::lang::Thread::currentThread();auto id=t?t->getId():0;std::unique_lock<std::mutex>l(queueMutex_);queue_.push_back(id);queueChanged_.wait(l,[&]{return queue_.front()==id&&(s?tryAcquireShared(a)>=0:tryAcquire(a));});queue_.pop_front();queueChanged_.notify_all();}
bool AbstractQueuedLongSynchronizer::timedAcquire_(::jxx::lang::jlong a,bool s,std::chrono::nanoseconds n){auto t=::jxx::lang::Thread::currentThread();auto id=t?t->getId():0;std::unique_lock<std::mutex>l(queueMutex_);queue_.push_back(id);auto ok=queueChanged_.wait_for(l,n,[&]{return queue_.front()==id&&(s?tryAcquireShared(a)>=0:tryAcquire(a));});auto it=std::find(queue_.begin(),queue_.end(),id);if(it!=queue_.end())queue_.erase(it);if(ok)queueChanged_.notify_all();return ok;}
::jxx::lang::jbool AbstractQueuedLongSynchronizer::hasQueuedThreads()const{std::lock_guard<std::mutex>l(queueMutex_);return!queue_.empty();}::jxx::lang::jlong AbstractQueuedLongSynchronizer::getQueueLength()const{std::lock_guard<std::mutex>l(queueMutex_);return static_cast<::jxx::lang::jlong>(queue_.size());}
::jxx::lang::jbool AbstractQueuedLongSynchronizer::tryAcquire(::jxx::lang::jlong){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedLongSynchronizer::tryRelease(::jxx::lang::jlong){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jlong AbstractQueuedLongSynchronizer::tryAcquireShared(::jxx::lang::jlong){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedLongSynchronizer::tryReleaseShared(::jxx::lang::jlong){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedLongSynchronizer::isHeldExclusively()const{throw ::jxx::lang::UnsupportedOperationException();}
}
