#include "util/concurrent/locks/jxx.util.concurrent.locks.AbstractQueuedSynchronizer.h"
#include <chrono>
#include "lang/jxx.lang.Class.h"
#include "lang/jxx.lang.Exceptions.h"
namespace jxx::util::concurrent::locks {
::jxx::Ptr<::jxx::lang::ClassAny>AbstractQueuedSynchronizer::Class(){return JxxClassInfoMarker::Class();}AbstractQueuedSynchronizer::AbstractQueuedSynchronizer():Super(){}
::jxx::lang::jint AbstractQueuedSynchronizer::getState()const noexcept{return state_.load(std::memory_order_acquire);}void AbstractQueuedSynchronizer::setState(::jxx::lang::jint v)noexcept{state_.store(v,std::memory_order_release);}::jxx::lang::jbool AbstractQueuedSynchronizer::compareAndSetState(::jxx::lang::jint e,::jxx::lang::jint u)noexcept{return state_.compare_exchange_strong(e,u,std::memory_order_acq_rel);}
void AbstractQueuedSynchronizer::acquire(::jxx::lang::jint a){if(!tryAcquire(a))queuedAcquire_(a,false);}void AbstractQueuedSynchronizer::acquireInterruptibly(::jxx::lang::jint a){acquire(a);}::jxx::lang::jbool AbstractQueuedSynchronizer::tryAcquireNanos(::jxx::lang::jint a,::jxx::lang::jlong n){return tryAcquire(a)||timedAcquire_(a,false,std::chrono::nanoseconds(n));}
::jxx::lang::jbool AbstractQueuedSynchronizer::release(::jxx::lang::jint a){if(!tryRelease(a))return false;queueChanged_.notify_all();return true;}void AbstractQueuedSynchronizer::acquireShared(::jxx::lang::jint a){if(tryAcquireShared(a)<0)queuedAcquire_(a,true);}void AbstractQueuedSynchronizer::acquireSharedInterruptibly(::jxx::lang::jint a){acquireShared(a);}::jxx::lang::jbool AbstractQueuedSynchronizer::tryAcquireSharedNanos(::jxx::lang::jint a,::jxx::lang::jlong n){return tryAcquireShared(a)>=0||timedAcquire_(a,true,std::chrono::nanoseconds(n));}::jxx::lang::jbool AbstractQueuedSynchronizer::releaseShared(::jxx::lang::jint a){if(!tryReleaseShared(a))return false;queueChanged_.notify_all();return true;}
void AbstractQueuedSynchronizer::queuedAcquire_(::jxx::lang::jint a,bool s){auto t=::jxx::lang::Thread::currentThread();auto id=t?t->getId():0;std::unique_lock<std::mutex>l(queueMutex_);queue_.push_back(id);queueChanged_.wait(l,[&]{return queue_.front()==id&&(s?tryAcquireShared(a)>=0:tryAcquire(a));});queue_.pop_front();queueChanged_.notify_all();}
bool AbstractQueuedSynchronizer::timedAcquire_(::jxx::lang::jint a,bool s,std::chrono::nanoseconds n){auto t=::jxx::lang::Thread::currentThread();auto id=t?t->getId():0;std::unique_lock<std::mutex>l(queueMutex_);queue_.push_back(id);auto ok=queueChanged_.wait_for(l,n,[&]{return queue_.front()==id&&(s?tryAcquireShared(a)>=0:tryAcquire(a));});auto it=std::find(queue_.begin(),queue_.end(),id);if(it!=queue_.end())queue_.erase(it);if(ok)queueChanged_.notify_all();return ok;}
::jxx::lang::jbool AbstractQueuedSynchronizer::hasQueuedThreads()const{std::lock_guard<std::mutex>l(queueMutex_);return!queue_.empty();}::jxx::lang::jint AbstractQueuedSynchronizer::getQueueLength()const{std::lock_guard<std::mutex>l(queueMutex_);return static_cast<::jxx::lang::jint>(queue_.size());}
::jxx::lang::jbool AbstractQueuedSynchronizer::tryAcquire(::jxx::lang::jint){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedSynchronizer::tryRelease(::jxx::lang::jint){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jint AbstractQueuedSynchronizer::tryAcquireShared(::jxx::lang::jint){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedSynchronizer::tryReleaseShared(::jxx::lang::jint){throw ::jxx::lang::UnsupportedOperationException();}::jxx::lang::jbool AbstractQueuedSynchronizer::isHeldExclusively()const{throw ::jxx::lang::UnsupportedOperationException();}
}
