#include "util/jxx.util.Base64.h"
#include "lang/jxx.lang.IllegalArgumentException.h"
#include "lang/jxx.lang.IndexOutOfBoundsException.h"
#include "lang/jxx.lang.NullPointerException.h"
#include <algorithm>
#include <array>
namespace jxx::util { namespace {
using B=::jxx::lang::jbyte; using BA=::jxx::lang::ByteArray;
BA arr(const std::vector<B>& v){auto a=::jxx::NEW<::jxx::lang::ByteArrayType>(static_cast<::jxx::lang::jint>(v.size()));for(size_t i=0;i<v.size();++i)(*a)[static_cast<::jxx::lang::jint>(i)]=v[i];return a;}
std::vector<B> vec(const BA& a){if(!a)throw ::jxx::lang::NullPointerException();std::vector<B> v;v.reserve(a->length);for(::jxx::lang::jint i=0;i<a->length;++i)v.push_back((*a)[i]);return v;}
std::vector<B> enc(const std::vector<B>& in,bool url,bool pad,int line,const std::vector<B>& sep){static const char* A="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";static const char* U="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";const char* t=url?U:A;std::vector<B> raw;for(size_t i=0;i<in.size();i+=3){unsigned n=(static_cast<unsigned char>(in[i])<<16);int rem=static_cast<int>(in.size()-i);if(rem>1)n|=static_cast<unsigned char>(in[i+1])<<8;if(rem>2)n|=static_cast<unsigned char>(in[i+2]);raw.push_back(t[(n>>18)&63]);raw.push_back(t[(n>>12)&63]);if(rem>1)raw.push_back(t[(n>>6)&63]);else if(pad)raw.push_back('=');if(rem>2)raw.push_back(t[n&63]);else if(pad)raw.push_back('=');}if(line>0&&!raw.empty()){std::vector<B> out;for(size_t i=0;i<raw.size();++i){if(i&&i%static_cast<size_t>(line)==0)out.insert(out.end(),sep.begin(),sep.end());out.push_back(raw[i]);}return out;}return raw;}
std::vector<B> dec(const std::vector<B>& input,bool url,bool mime){std::array<int,256>d;d.fill(-1);std::string a=url?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";for(int i=0;i<64;++i)d[static_cast<unsigned char>(a[i])]=i;std::vector<unsigned char>s;for(B b:input){auto c=static_cast<unsigned char>(b);if(d[c]>=0||c=='=')s.push_back(c);else if(!mime)throw ::jxx::lang::IllegalArgumentException();}if(s.size()%4==1)throw ::jxx::lang::IllegalArgumentException();size_t eq=0;while(!s.empty()&&s.back()=='='){++eq;s.pop_back();}if(eq>2||(!s.empty()&&std::find(s.begin(),s.end(),'=')!=s.end()))throw ::jxx::lang::IllegalArgumentException();std::vector<B> out;unsigned acc=0;int bits=0;for(auto c:s){int v=d[c];if(v<0)throw ::jxx::lang::IllegalArgumentException();acc=(acc<<6)|static_cast<unsigned>(v);bits+=6;if(bits>=8){bits-=8;out.push_back(static_cast<B>((acc>>bits)&255));}}return out;}
}
Base64::Encoder::Encoder(::jxx::lang::jbool u,::jxx::lang::jbool p,::jxx::lang::jint l,const BA&s):url_(u),padding_(p),lineLength_(l),separator_(s){}
Base64::Decoder::Decoder(::jxx::lang::jbool u,::jxx::lang::jbool m):url_(u),mime_(m){}
::jxx::Ptr<Base64::Encoder> Base64::getEncoder(){return ::jxx::NEW<Encoder>(false,true,0,BA{});}::jxx::Ptr<Base64::Encoder> Base64::getUrlEncoder(){return ::jxx::NEW<Encoder>(true,true,0,BA{});}::jxx::Ptr<Base64::Encoder> Base64::getMimeEncoder(){auto s=::jxx::NEW<::jxx::lang::ByteArrayType>(2);(*s)[0]='\r';(*s)[1]='\n';return ::jxx::NEW<Encoder>(false,true,76,s);}
::jxx::Ptr<Base64::Encoder> Base64::getMimeEncoder(::jxx::lang::jint n,const BA&s){if(!s)throw ::jxx::lang::NullPointerException();if(n<=0)return ::jxx::NEW<Encoder>(false,true,0,s);n=(n/4)*4;if(n<=0)throw ::jxx::lang::IllegalArgumentException();for(auto b:vec(s)){if((b>='A'&&b<='Z')||(b>='a'&&b<='z')||(b>='0'&&b<='9')||b=='+'||b=='/'||b=='=')throw ::jxx::lang::IllegalArgumentException();}return ::jxx::NEW<Encoder>(false,true,n,s);}
::jxx::Ptr<Base64::Decoder> Base64::getDecoder(){return ::jxx::NEW<Decoder>(false,false);}::jxx::Ptr<Base64::Decoder> Base64::getUrlDecoder(){return ::jxx::NEW<Decoder>(true,false);}::jxx::Ptr<Base64::Decoder> Base64::getMimeDecoder(){return ::jxx::NEW<Decoder>(false,true);}
BA Base64::Encoder::encode(const BA&s)const{return arr(enc(vec(s),url_,padding_,lineLength_,separator_?vec(separator_):std::vector<B>{}));}::jxx::lang::jint Base64::Encoder::encode(const BA&s,const BA&d)const{if(!d)throw ::jxx::lang::NullPointerException();auto r=encode(s);if(d->length<r->length)throw ::jxx::lang::IllegalArgumentException();for(int i=0;i<r->length;++i)(*d)[i]=(*r)[i];return r->length;}
::jxx::Ptr<::jxx::lang::String> Base64::Encoder::encodeToString(const BA&s)const{auto r=encode(s);std::string x;for(int i=0;i<r->length;++i)x.push_back(static_cast<char>((*r)[i]));return ::jxx::NEW<::jxx::lang::String>(x);}::jxx::Ptr<Base64::Encoder> Base64::Encoder::withoutPadding()const{return ::jxx::NEW<Encoder>(url_,false,lineLength_,separator_);}::jxx::Ptr<::jxx::nio::ByteBuffer> Base64::Encoder::encode(const ::jxx::Ptr<::jxx::nio::ByteBuffer>&b)const{if(!b)throw ::jxx::lang::NullPointerException();auto a=::jxx::NEW<::jxx::lang::ByteArrayType>(b->remaining());for(int i=0;i<a->length;++i)(*a)[i]=b->get();return ::jxx::nio::ByteBuffer::wrap(encode(a));}
::jxx::Ptr<::jxx::io::OutputStream> Base64::Encoder::wrap(const ::jxx::Ptr<::jxx::io::OutputStream>&o)const{if(!o)throw ::jxx::lang::NullPointerException();return ::jxx::NEW<Base64EncodingOutputStream>(o,std::const_pointer_cast<Encoder>(getThis<const Encoder>()));}
BA Base64::Decoder::decode(const BA&s)const{return arr(dec(vec(s),url_,mime_));}::jxx::lang::jint Base64::Decoder::decode(const BA&s,const BA&d)const{if(!d)throw ::jxx::lang::NullPointerException();auto r=decode(s);if(d->length<r->length)throw ::jxx::lang::IllegalArgumentException();for(int i=0;i<r->length;++i)(*d)[i]=(*r)[i];return r->length;}BA Base64::Decoder::decode(const ::jxx::Ptr<::jxx::lang::String>&s)const{if(!s)throw ::jxx::lang::NullPointerException();auto v=s->utf8();auto a=::jxx::NEW<::jxx::lang::ByteArrayType>(static_cast<int>(v.size()));for(size_t i=0;i<v.size();++i)(*a)[static_cast<int>(i)]=v[i];return decode(a);}::jxx::Ptr<::jxx::nio::ByteBuffer> Base64::Decoder::decode(const ::jxx::Ptr<::jxx::nio::ByteBuffer>&b)const{if(!b)throw ::jxx::lang::NullPointerException();auto a=::jxx::NEW<::jxx::lang::ByteArrayType>(b->remaining());for(int i=0;i<a->length;++i)(*a)[i]=b->get();return ::jxx::nio::ByteBuffer::wrap(decode(a));}::jxx::Ptr<::jxx::io::InputStream> Base64::Decoder::wrap(const ::jxx::Ptr<::jxx::io::InputStream>&i)const{if(!i)throw ::jxx::lang::NullPointerException();return ::jxx::NEW<Base64DecodingInputStream>(i,std::const_pointer_cast<Decoder>(getThis<const Decoder>()));}
Base64EncodingOutputStream::Base64EncodingOutputStream(const ::jxx::Ptr<::jxx::io::OutputStream>&o,const ::jxx::Ptr<Base64::Encoder>&e):out_(o),encoder_(e){}void Base64EncodingOutputStream::write(::jxx::lang::jint v){if(closed_)throw ::jxx::lang::IllegalArgumentException();pending_.push_back(static_cast<B>(v));}void Base64EncodingOutputStream::write(const BA&b){write(b,0,b?b->length:0);}void Base64EncodingOutputStream::write(const BA&b,int o,int n){if(!b)throw ::jxx::lang::NullPointerException();if(o<0||n<0||o>b->length-n)throw ::jxx::lang::IndexOutOfBoundsException();for(int i=0;i<n;++i)pending_.push_back((*b)[o+i]);}void Base64EncodingOutputStream::flush(){out_->flush();}void Base64EncodingOutputStream::close(){if(closed_)return;auto r=encoder_->encode(arr(pending_));out_->write(r);out_->close();closed_=true;}
Base64DecodingInputStream::Base64DecodingInputStream(const ::jxx::Ptr<::jxx::io::InputStream>&i,const ::jxx::Ptr<Base64::Decoder>&d):in_(i),decoder_(d){}void Base64DecodingInputStream::load_(){if(loaded_)return;std::vector<B>v;for(int x;(x=in_->read())>=0;)v.push_back(static_cast<B>(x));decoded_=decoder_->decode(arr(v));loaded_=true;}int Base64DecodingInputStream::read(){load_();return position_>=decoded_->length?-1:static_cast<unsigned char>((*decoded_)[position_++]);}int Base64DecodingInputStream::read(const BA&b,int o,int n){if(!b)throw ::jxx::lang::NullPointerException();if(o<0||n<0||o>b->length-n)throw ::jxx::lang::IndexOutOfBoundsException();load_();if(position_>=decoded_->length)return -1;int k=std::min(n,decoded_->length-position_);for(int i=0;i<k;++i)(*b)[o+i]=(*decoded_)[position_++];return k;}int Base64DecodingInputStream::available(){load_();return decoded_->length-position_;}void Base64DecodingInputStream::close(){in_->close();}
} // namespace jxx::util
