#pragma once

#include "util/jxx.util.NoSuchElementException.h"
#include "util/jxx.util.ConcurrentModificationException.h"
#include "util/jxx.util.EmptyStackException.h"
#include "util/jxx.util.IllegalFormatException.h"
#include "util/jxx.util.MissingFormatArgumentException.h"
#include "util/jxx.util.IllegalFormatConversionException.h"
#include "util/jxx.util.IllegalFormatFlagsException.h"
#include "util/jxx.util.IllegalFormatPrecisionException.h"
#include "util/jxx.util.IllegalFormatWidthException.h"
#include "util/jxx.util.UnknownFormatConversionException.h"
#include "util/jxx.util.UnknownFormatFlagsException.h"
#include "util/jxx.util.DuplicateFormatFlagsException.h"
#include "util/jxx.util.FormatFlagsConversionMismatchException.h"
#include "util/jxx.util.IllegalFormatCodePointException.h"
#include "util/jxx.util.TooManyListenersException.h"
