#pragma once
#include "io/jxx.io.SerializableI.h"
#include "lang/jxx.lang.ClassInfo.h"
#include "util/jxx.util.AbstractCollection.h"
#include "util/jxx.util.Deque.h"
#include "util/jxx.util.concurrent.LinkedBlockingDeque.h"
namespace jxx::util::concurrent {
template<typename E> class ConcurrentLinkedDeque final:public ::jxx::lang::ClassBase<ConcurrentLinkedDeque<E>,::jxx::util::AbstractCollection<E>,::jxx::util::Deque<E>,::jxx::io::SerializableI>{
public:using JxxSuper=::jxx::util::AbstractCollection<E>;using Super=::jxx::lang::ClassBase<ConcurrentLinkedDeque<E>,JxxSuper,::jxx::util::Deque<E>,::jxx::io::SerializableI>;using JxxClassInfoMarker=typename Super::JxxClassInfoMarker;static ::jxx::Ptr<::jxx::lang::ClassAny>Class(){return JxxClassInfoMarker::Class();}ConcurrentLinkedDeque():Super(),delegate_(::jxx::NEW<LinkedBlockingDeque<E>>()){}
 void addFirst(const ::jxx::Ptr<E>&e)override{delegate_->addFirst(e);}void addLast(const ::jxx::Ptr<E>&e)override{delegate_->addLast(e);}::jxx::lang::jbool offerFirst(const ::jxx::Ptr<E>&e)override{return delegate_->offerFirst(e);}::jxx::lang::jbool offerLast(const ::jxx::Ptr<E>&e)override{return delegate_->offerLast(e);}::jxx::Ptr<E>removeFirst()override{return delegate_->removeFirst();}::jxx::Ptr<E>removeLast()override{return delegate_->removeLast();}::jxx::Ptr<E>pollFirst()override{return delegate_->pollFirst();}::jxx::Ptr<E>pollLast()override{return delegate_->pollLast();}::jxx::Ptr<E>getFirst()override{return delegate_->getFirst();}::jxx::Ptr<E>getLast()override{return delegate_->getLast();}::jxx::Ptr<E>peekFirst()override{return delegate_->peekFirst();}::jxx::Ptr<E>peekLast()override{return delegate_->peekLast();}::jxx::lang::jbool removeFirstOccurrence(const ::jxx::Ptr<::jxx::lang::Object>&o)override{return delegate_->removeFirstOccurrence(o);}::jxx::lang::jbool removeLastOccurrence(const ::jxx::Ptr<::jxx::lang::Object>&o)override{return delegate_->removeLastOccurrence(o);}void push(const ::jxx::Ptr<E>&e)override{delegate_->push(e);}::jxx::Ptr<E>pop()override{return delegate_->pop();}::jxx::Ptr<::jxx::util::Iterator<E>>descendingIterator()override{return delegate_->descendingIterator();}
 ::jxx::lang::jbool offer(const ::jxx::Ptr<E>&e)override{return delegate_->offer(e);}::jxx::Ptr<E>poll()override{return delegate_->poll();}::jxx::Ptr<E>remove()override{return delegate_->removeFirst();}::jxx::Ptr<E>element()override{return delegate_->getFirst();}::jxx::Ptr<E>peek()override{return delegate_->peek();}::jxx::lang::jint size()override{return delegate_->size();}::jxx::Ptr<::jxx::util::Iterator<E>>iterator()override{return delegate_->iterator();}::jxx::lang::jbool contains(const ::jxx::Ptr<::jxx::lang::Object>&o)override{return delegate_->contains(o);}::jxx::lang::jbool remove(const ::jxx::Ptr<::jxx::lang::Object>&o)override{return delegate_->remove(o);}void clear()override{delegate_->clear();}
 void writeObject(const ::jxx::Ptr<::jxx::io::ObjectOutputStream>&o)override{(void)o;}void readObject(const ::jxx::Ptr<::jxx::io::ObjectInputStream>&i)override{(void)i;}void readObjectNoData()override{}
private: ::jxx::Ptr<LinkedBlockingDeque<E>>delegate_;};}
