#include "swing/jxx.swing.JInternalFrame.h"
#include "swing/jxx.swing.JLayeredPane.h"
#include "swing/jxx.swing.JRootPane.h"
namespace jxx::swing
{
    namespace { ::jxx::Ptr<::jxx::lang::String> emptyTitle(){ return ::jxx::NEW<::jxx::lang::String>(""); } }
    JInternalFrame::JInternalFrame():JInternalFrame(emptyTitle()){} JInternalFrame::JInternalFrame(const ::jxx::Ptr<::jxx::lang::String>& t):JInternalFrame(t,false,false,false,false){}
    JInternalFrame::JInternalFrame(const ::jxx::Ptr<::jxx::lang::String>& t,::jxx::lang::jbool r,::jxx::lang::jbool c,::jxx::lang::jbool m,::jxx::lang::jbool i):Super(),rootPane_(::jxx::NEW<JRootPane>()),title_(t?t:emptyTitle()),resizable_(r),closable_(c),maximizable_(m),iconifiable_(i){JComponent::add(rootPane_);}
    ::jxx::Ptr<JRootPane> JInternalFrame::getRootPane()const{return rootPane_;}void JInternalFrame::setContentPane(const ::jxx::Ptr<::jxx::awt::Container>& p){rootPane_->setContentPane(p);}::jxx::Ptr<::jxx::awt::Container> JInternalFrame::getContentPane()const{return rootPane_->getContentPane();}void JInternalFrame::setLayeredPane(const ::jxx::Ptr<JLayeredPane>& p){rootPane_->setLayeredPane(p);}::jxx::Ptr<JLayeredPane> JInternalFrame::getLayeredPane()const{return rootPane_->getLayeredPane();}void JInternalFrame::setGlassPane(const ::jxx::Ptr<::jxx::awt::Component>& p){rootPane_->setGlassPane(p);}::jxx::Ptr<::jxx::awt::Component> JInternalFrame::getGlassPane()const{return rootPane_->getGlassPane();}
    void JInternalFrame::setTitle(const ::jxx::Ptr<::jxx::lang::String>& v){title_=v?v:emptyTitle();}::jxx::Ptr<::jxx::lang::String> JInternalFrame::getTitle()const{return title_;}void JInternalFrame::setClosed(::jxx::lang::jbool v){closed_=v;if(v)setVisible(false);}::jxx::lang::jbool JInternalFrame::isClosed()const{return closed_;}void JInternalFrame::setIcon(::jxx::lang::jbool v){icon_=v;}::jxx::lang::jbool JInternalFrame::isIcon()const{return icon_;}void JInternalFrame::setMaximum(::jxx::lang::jbool v){maximum_=v;}::jxx::lang::jbool JInternalFrame::isMaximum()const{return maximum_;}void JInternalFrame::setSelected(::jxx::lang::jbool v){selected_=v;}::jxx::lang::jbool JInternalFrame::isSelected()const{return selected_;}
    ::jxx::lang::jbool JInternalFrame::isResizable()const{return resizable_;}::jxx::lang::jbool JInternalFrame::isClosable()const{return closable_;}::jxx::lang::jbool JInternalFrame::isMaximizable()const{return maximizable_;}::jxx::lang::jbool JInternalFrame::isIconifiable()const{return iconifiable_;}void JInternalFrame::dispose(){setClosed(true);}void JInternalFrame::moveToFront(){if(auto p=::jxx::CAST<JLayeredPane>(getParent()))p->moveToFront(::jxx::CAST<::jxx::awt::Component>(thisPtr()));}void JInternalFrame::moveToBack(){if(auto p=::jxx::CAST<JLayeredPane>(getParent()))p->moveToBack(::jxx::CAST<::jxx::awt::Component>(thisPtr()));}
}
