#include "com/sun/net/httpserver/internal/jxx.com.sun.net.httpserver.internal.DefaultHttpServer.h"
#include "com/sun/net/httpserver/internal/jxx.com.sun.net.httpserver.internal.DefaultHttpContext.h"
#include "com/sun/net/httpserver/jxx.com.sun.net.httpserver.HttpHandler.h"
#include "lang/jxx.lang.Exceptions.h"
#include "net/jxx.net.InetSocketAddress.h"
#include "net/jxx.net.Socket.h"
namespace jxx::com::sun::net::httpserver::internal {
DefaultHttpServer::DefaultHttpServer():Super(),serverSocket_(::jxx::NEW<::jxx::net::ServerSocket>()){}DefaultHttpServer::DefaultHttpServer(const ::jxx::Ptr<::jxx::net::InetSocketAddress>&a,::jxx::lang::jint b):DefaultHttpServer(){bind(a,b);}DefaultHttpServer::~DefaultHttpServer(){stop(0);}
void DefaultHttpServer::bind(const ::jxx::Ptr<::jxx::net::InetSocketAddress>&a,::jxx::lang::jint b){if(!a)throw ::jxx::lang::NullPointerException();if(address_)throw ::jxx::lang::IllegalStateException();serverSocket_->bind(a,b);address_=a;}void DefaultHttpServer::start(){if(!address_||running_.exchange(true))throw ::jxx::lang::IllegalStateException();acceptThread_=std::thread(&DefaultHttpServer::acceptLoop,this);}void DefaultHttpServer::stop(::jxx::lang::jint){if(!running_.exchange(false))return;serverSocket_->close();if(acceptThread_.joinable())acceptThread_.join();for(auto&t:workers_)if(t.joinable())t.join();workers_.clear();}
void DefaultHttpServer::setExecutor(const ::jxx::Ptr<::jxx::util::concurrent::Executor>&e){if(running_)throw ::jxx::lang::IllegalStateException();executor_=e;}::jxx::Ptr<::jxx::util::concurrent::Executor>DefaultHttpServer::getExecutor(){return executor_;}
::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpContext>DefaultHttpServer::createContext(const ::jxx::Ptr<::jxx::lang::String>&p,const ::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpHandler>&h){auto c=::jxx::NEW<DefaultHttpContext>(::jxx::CAST<::jxx::com::sun::net::httpserver::HttpServer>(this->thisPtr()),p,h);std::lock_guard<std::mutex>lock(mutex_);for(auto&e:contexts_)if(e->getPath()->equals(p))throw ::jxx::lang::IllegalArgumentException();contexts_.push_back(c);return c;}::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpContext>DefaultHttpServer::createContext(const ::jxx::Ptr<::jxx::lang::String>&p){return createContext(p,nullptr);}
void DefaultHttpServer::removeContext(const ::jxx::Ptr<::jxx::lang::String>&p){std::lock_guard<std::mutex>lock(mutex_);for(auto i=contexts_.begin();i!=contexts_.end();++i)if((*i)->getPath()->equals(p)){contexts_.erase(i);return;}throw ::jxx::lang::IllegalArgumentException();}void DefaultHttpServer::removeContext(const ::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpContext>&c){if(!c)throw ::jxx::lang::NullPointerException();removeContext(c->getPath());}::jxx::Ptr<::jxx::net::InetSocketAddress>DefaultHttpServer::getAddress(){return address_;}
void DefaultHttpServer::acceptLoop(){while(running_){try{auto s=serverSocket_->accept();workers_.emplace_back(&DefaultHttpServer::serve,this,s);}catch(...){if(running_)continue;}}}void DefaultHttpServer::serve(const ::jxx::Ptr<::jxx::net::Socket>&s){if(s)s->close();}::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpContext>DefaultHttpServer::match(const std::string&p){std::lock_guard<std::mutex>lock(mutex_);::jxx::Ptr<::jxx::com::sun::net::httpserver::HttpContext>best;std::size_t n=0;for(auto&c:contexts_){auto q=c->getPath()->utf8();if(p.compare(0,q.size(),q)==0&&q.size()>n){best=c;n=q.size();}}return best;}
}
