#include "ext/net/ssl/internal/jxx.ext.net.ssl.internal.OpenSslServerSocket.h"

#include "ext/net/ssl/internal/jxx.ext.net.ssl.internal.OpenSslContextConfig.h"
#include "ext/net/ssl/internal/jxx.ext.net.ssl.internal.OpenSslSocket.h"
#include "lang/jxx.lang.IllegalArgumentException.h"

namespace jxx::ext::net::ssl::internal {
namespace {
::jxx::Ptr<OpenSslServerSocket::StringArray> toArray(const std::vector<std::string>& values){auto r=::jxx::NEW<OpenSslServerSocket::StringArray>(static_cast<::jxx::lang::jint>(values.size()));for(std::size_t i=0;i<values.size();++i)(*r)[static_cast<::jxx::lang::jint>(i)]=::jxx::NEW<::jxx::lang::String>(values[i]);return r;}
std::vector<std::string> toVector(const ::jxx::Ptr<OpenSslServerSocket::StringArray>& values){if(values==nullptr)throw ::jxx::lang::IllegalArgumentException();std::vector<std::string> r;for(::jxx::lang::jint i=0;i<values->length;++i){if((*values)[i]==nullptr)throw ::jxx::lang::IllegalArgumentException();r.push_back((*values)[i]->utf8());}return r;}
}
OpenSslServerSocket::OpenSslServerSocket(::jxx::lang::jint port,::jxx::lang::jint backlog,const ::jxx::Ptr<::jxx::net::InetAddress>& address,const std::shared_ptr<OpenSslContextConfig>& config):Super(port,backlog,address),config_(config){}
::jxx::Ptr<::jxx::net::Socket> OpenSslServerSocket::accept(){auto transport=::jxx::net::ServerSocket::accept();auto socket=::jxx::NEW<OpenSslSocket>(transport,::jxx::NEW<::jxx::lang::String>(""),transport->getPort(),true,std::vector<unsigned char>(),config_);socket->setUseClientMode(false);socket->setNeedClientAuth(needClientAuth_);socket->setWantClientAuth(wantClientAuth_);socket->setEnableSessionCreation(enableSessionCreation_);if(!enabledProtocols_.empty())socket->setEnabledProtocols(toArray(enabledProtocols_));if(!enabledCipherSuites_.empty())socket->setEnabledCipherSuites(toArray(enabledCipherSuites_));return socket;}
::jxx::Ptr<OpenSslServerSocket::StringArray> OpenSslServerSocket::getEnabledCipherSuites()const{return toArray(enabledCipherSuites_);}void OpenSslServerSocket::setEnabledCipherSuites(const ::jxx::Ptr<StringArray>&v){enabledCipherSuites_=toVector(v);}::jxx::Ptr<OpenSslServerSocket::StringArray> OpenSslServerSocket::getSupportedCipherSuites()const{return toArray(enabledCipherSuites_);}::jxx::Ptr<OpenSslServerSocket::StringArray> OpenSslServerSocket::getEnabledProtocols()const{return toArray(enabledProtocols_);}void OpenSslServerSocket::setEnabledProtocols(const ::jxx::Ptr<StringArray>&v){enabledProtocols_=toVector(v);}::jxx::Ptr<OpenSslServerSocket::StringArray> OpenSslServerSocket::getSupportedProtocols()const{return toArray({"TLSv1.2","TLSv1.3"});}
void OpenSslServerSocket::setNeedClientAuth(::jxx::lang::jbool v){needClientAuth_=v;if(v)wantClientAuth_=false;}::jxx::lang::jbool OpenSslServerSocket::getNeedClientAuth()const{return needClientAuth_;}void OpenSslServerSocket::setWantClientAuth(::jxx::lang::jbool v){wantClientAuth_=v;if(v)needClientAuth_=false;}::jxx::lang::jbool OpenSslServerSocket::getWantClientAuth()const{return wantClientAuth_;}void OpenSslServerSocket::setUseClientMode(::jxx::lang::jbool v){useClientMode_=v;}::jxx::lang::jbool OpenSslServerSocket::getUseClientMode()const{return useClientMode_;}void OpenSslServerSocket::setEnableSessionCreation(::jxx::lang::jbool v){enableSessionCreation_=v;}::jxx::lang::jbool OpenSslServerSocket::getEnableSessionCreation()const{return enableSessionCreation_;}
}
