#include "io/jxx.io.ModifiedUTF.h"
#include <cstdint>
#include <vector>
#include "io/jxx.io.UTFDataFormatException.h"
#include "lang/jxx.lang.NullPointerException.h"
#include "lang/jxx.lang.String.h"
namespace jxx::io {
::jxx::lang::ByteArray ModifiedUTF::encode(const ::jxx::Ptr<::jxx::lang::String>& s){if(!s)throw ::jxx::lang::NullPointerException();std::vector<::jxx::lang::jbyte> v;for(::jxx::lang::jint i=0;i<s->length();++i){auto c=static_cast<std::uint16_t>(s->charAt(i));if(c>=1&&c<=0x7f)v.push_back(static_cast<::jxx::lang::jbyte>(c));else if(c<=0x7ff){v.push_back(static_cast<::jxx::lang::jbyte>(0xc0|((c>>6)&0x1f)));v.push_back(static_cast<::jxx::lang::jbyte>(0x80|(c&0x3f)));}else{v.push_back(static_cast<::jxx::lang::jbyte>(0xe0|((c>>12)&0x0f)));v.push_back(static_cast<::jxx::lang::jbyte>(0x80|((c>>6)&0x3f)));v.push_back(static_cast<::jxx::lang::jbyte>(0x80|(c&0x3f)));}}auto b=::jxx::NEW<::jxx::lang::ByteArrayType>(static_cast<std::uint32_t>(v.size()));for(std::size_t i=0;i<v.size();++i)(*b)[static_cast<::jxx::lang::jint>(i)]=v[i];return b;}
::jxx::Ptr<::jxx::lang::String> ModifiedUTF::decode(const ::jxx::lang::ByteArray& b){if(!b)throw ::jxx::lang::NullPointerException();std::u16string s;std::size_t i=0;while(i<b->length){auto a=static_cast<unsigned char>((*b)[static_cast<::jxx::lang::jint>(i++)]);if((a&0x80)==0){s.push_back(static_cast<char16_t>(a));}else if((a&0xe0)==0xc0){if(i>=b->length)throw UTFDataFormatException();auto c=static_cast<unsigned char>((*b)[static_cast<::jxx::lang::jint>(i++)]);if((c&0xc0)!=0x80)throw UTFDataFormatException();s.push_back(static_cast<char16_t>(((a&0x1f)<<6)|(c&0x3f)));}else if((a&0xf0)==0xe0){if(i+1>=b->length)throw UTFDataFormatException();auto c=static_cast<unsigned char>((*b)[static_cast<::jxx::lang::jint>(i++)]);auto d=static_cast<unsigned char>((*b)[static_cast<::jxx::lang::jint>(i++)]);if((c&0xc0)!=0x80||(d&0xc0)!=0x80)throw UTFDataFormatException();s.push_back(static_cast<char16_t>(((a&0x0f)<<12)|((c&0x3f)<<6)|(d&0x3f)));}else throw UTFDataFormatException();}return ::jxx::NEW<::jxx::lang::String>(s);}
}
