
#include <cstring>
#include "io/jxx.io.RandomAccessFile.h"
#include "io/jxx.io.FileNotFoundException.h"
#include "io/jxx.io.EOFException.h"
#include "io/jxx.io.UTFDataFormatException.h"
namespace jxx { namespace io {
RandomAccessFile::RandomAccessFile(const std::string& path, const std::string& mode){ std::ios::openmode m{}; if(mode=="r"){ m=std::ios::in|std::ios::binary; } else if(mode=="rw"){ m=std::ios::in|std::ios::out|std::ios::binary;} else { throw IOException("RandomAccessFile: invalid mode "+mode);} fs.open(path,m); if(!fs.is_open()) throw FileNotFoundException("RandomAccessFile: cannot open "+path);} 
void RandomAccessFile::close(){ if(fs.is_open()) fs.close(); }
jxx::lang::jlong RandomAccessFile::getFilePointer(){ return (jxx::lang::jlong)fs.tellg(); }
void RandomAccessFile::seek(jxx::lang::jlong pos){ fs.seekg(pos); fs.seekp(pos); if(!fs) throw IOException("RandomAccessFile.seek failed"); }
jxx::lang::jlong RandomAccessFile::length(){ auto cur=fs.tellg(); fs.seekg(0,std::ios::end); auto end=fs.tellg(); fs.seekg(cur); return (jxx::lang::jlong)end; }
void RandomAccessFile::setLength(jxx::lang::jlong newLen){ jxx::lang::jlong len=length(); if(newLen < len){ throw IOException("RandomAccessFile.setLength shrink not supported"); } else if(newLen > len){ seek(len); ByteArray zeros((size_t)(newLen-len),0); write(zeros);} }
void RandomAccessFile::write(int b){ char c=(char)(b&0xFF); fs.write(&c,1); if(!fs) throw IOException("RandomAccessFile.write failed"); }
void RandomAccessFile::write(const ByteArray& b){ write(b,0,(int)b.size()); }
void RandomAccessFile::write(const ByteArray& b, int off, int len){ if(b.size()< (size_t)off + (size_t)len) throw IOException("IndexOutOfBounds in RandomAccessFile.write"); fs.write((const char*)(b.data()+off), len); if(!fs) throw IOException("RandomAccessFile.write failed"); }
void RandomAccessFile::writeBoolean(bool v){ write(v?1:0);} void RandomAccessFile::writeByte(int v){ write(v);}
void RandomAccessFile::writeShort(int v){ ByteArray t{ (jbyte)((v>>8)&0xFF), (jbyte)(v&0xFF)}; write(t);}
void RandomAccessFile::writeChar(int v){ writeShort(v);} void RandomAccessFile::writeInt(int v){ ByteArray t(4); t[0]=(uint8_t)((v>>24)&0xFF); t[1]=(uint8_t)((v>>16)&0xFF); t[2]=(uint8_t)((v>>8)&0xFF); t[3]=(uint8_t)(v&0xFF); write(t);} void RandomAccessFile::writeLong(jxx::lang::jlong v){ ByteArray t(8); for(int i=7;i>=0;--i){ t[7-i]=(uint8_t)((v>>(i*8))&0xFF);} write(t);} void RandomAccessFile::writeFloat(float v){ uint32_t bits; std::memcpy(&bits,&v,4); writeInt((int)bits);} void RandomAccessFile::writeDouble(double v){ uint64_t bits; std::memcpy(&bits,&v,8); writeLong((jxx::lang::jlong)bits);} 
void RandomAccessFile::writeUTF(const std::u16string& s){ ByteArray enc=ModifiedUTF::encode(s); if(enc.size()>65535) throw UTFDataFormatException("writeUTF: length exceeds 65535"); 
writeShort((int)enc.size()); write(enc);} void RandomAccessFile::readFully(ByteArray& b){ readFully(b,0,(int)b.size()); } void RandomAccessFile::readFully(ByteArray& b, int off, int len){ if(b.size()< (size_t)off + (size_t)len) throw IOException("IndexOutOfBounds in RandomAccessFile.readFully"); char* dst=(char*)(b.data()+off); fs.read(dst,len); if(fs.gcount()!=len) throw EOFException("readFully: EOF"); } int RandomAccessFile::skipBytes(int n){ auto cur=fs.tellg(); fs.seekg(n,std::ios::cur); return (int)(fs.tellg()-cur);} bool RandomAccessFile::readBoolean(){ int b=readUnsignedByte(); return b!=0;} jxx::lang::jbyte RandomAccessFile::readByte(){ char c; fs.read(&c,1); if(!fs) throw EOFException("readByte: EOF"); return (jxx::lang::jbyte)(unsigned char)c;} char RandomAccessFile::readUnsignedByte(){ int v=readByte(); return (char)(v&0xFF);} jxx::lang::jshort RandomAccessFile::readShort(){ ByteArray b(2); readFully(b); return (jxx::lang::jshort)((b[0]<<8)|b[1]); } unsigned short RandomAccessFile::readUnsignedShort(){ ByteArray b(2); readFully(b); return (unsigned short)((b[0]<<8)|b[1]); } jxx::lang::jchar RandomAccessFile::readChar(){ return (jxx::lang::jchar)readUnsignedShort(); } int RandomAccessFile::readInt(){ ByteArray b(4); readFully(b); return ((int)b[0]<<24)|((int)b[1]<<16)|((int)b[2]<<8)|((int)b[3]); } jxx::lang::jlong RandomAccessFile::readLong(){ ByteArray b(8); readFully(b); jxx::lang::jlong v=0; for(int i=0;i<8;++i) v=(v<<8)|b[i]; return v;} float RandomAccessFile::readFloat(){ uint32_t bits=(uint32_t)readInt(); float f; std::memcpy(&f,&bits,4); return f;} double RandomAccessFile::readDouble(){ uint64_t bits=(uint64_t)readLong(); double d; std::memcpy(&d,&bits,8); return d;} std::u16string RandomAccessFile::readUTF(){ unsigned short utflen=readUnsignedShort(); ByteArray bytes(utflen); readFully(bytes); return ModifiedUTF::decode(bytes); }
}}
