#pragma once

#include <type_traits>

#include "lang/jxx.lang.Class.h"
#include "lang/jxx.lang.ClassInfo.h"
#include "lang/jxx.lang.ClassInfoMarker.h"
#include "lang/jxx.lang.Object.h"

namespace jxx::lang {

/**
 * Registers a type which inherits the unified ClassInfo<T> mixin.
 *
 * This function works for both Object-derived Java classes and pure-virtual
 * Java interfaces. Category detection is performed by ClassInfo<T>.
 */
template <typename T>
jxx::Ptr<ClassAny> registerClass() {
    static_assert(
        class_info_detail::HasClassInfo<T>::value,
        "registerClass<T>() requires T to inherit ClassInfo<T>.");

    return ClassInfo<T>::Class();
}

/** Java-style class-literal helper for generic code. */
template <typename T>
jxx::Ptr<ClassAny> classOf() {
    return registerClass<T>();
}

/** Returns true when T is registered and its canonical descriptor exists. */
template <typename T>
jbool isClassRegistered() {
    static_assert(
        class_info_detail::HasClassInfo<T>::value,
        "isClassRegistered<T>() requires T to inherit ClassInfo<T>.");

    try {
        const auto descriptor = ClassAny::forType(
            std::type_index(typeid(T)));
        return descriptor != nullptr;
    } catch (const IllegalStateException&) {
        return false;
    }
}

} // namespace jxx::lang

#ifndef JXX_DETAIL_CAT_IMPL
#define JXX_DETAIL_CAT_IMPL(a, b) a##b
#endif

#ifndef JXX_DETAIL_CAT
#define JXX_DETAIL_CAT(a, b) JXX_DETAIL_CAT_IMPL(a, b)
#endif

/**
 * Optional eager registration macro.
 *
 * Most Object-derived classes register through jxx::NEW<T>(). Interfaces and
 * classes which need registration before first construction may use this.
 */
#define JXX_REGISTER_TYPE(T)                                                     \
namespace {                                                                      \
    [[maybe_unused]] inline const bool                                           \
    JXX_DETAIL_CAT(jxx_classinfo_registration_, __COUNTER__) =                   \
        (::jxx::lang::registerClass<T>() != nullptr);                            \
}

/** Compatibility aliases. Names are generated by ClassInfo<T>. */
#define JXX_REGISTER_CLASS(T) JXX_REGISTER_TYPE(T)
#define JXX_REGISTER_INTERFACE(T) JXX_REGISTER_TYPE(T)

/**
 * The unified ClassInfo implementation detects abstract classes automatically.
 * This compatibility macro intentionally performs no metadata mutation.
 */
#define JXX_MARK_ABSTRACT(T)                                                     \
    static_assert(std::is_abstract_v<T>,                                         \
        "JXX_MARK_ABSTRACT requires an abstract C++ type")
