#include "awt/jxx.awt.Window.h"
#include <algorithm>
#include "awt/event/jxx.awt.event.WindowEvent.h"
#include "awt/event/jxx.awt.event.WindowFocusListener.h"
#include "awt/event/jxx.awt.event.WindowListener.h"
#include "awt/event/jxx.awt.event.WindowStateListener.h"
#include "gui/internal/jxx.gui.internal.NativeWindow.h"
namespace jxx::awt {Window::Window():active_(false),displayable_(false){Component::setVisible(false);}Window::~Window(){dispose();}void Window::ensureNativeWindow(){}void Window::configureNativeEvents(){if(!nativeWindow_)return;std::weak_ptr<Window> self=::jxx::CAST<Window>(thisPtr());nativeWindow_->setEventCallback([self](::jxx::lang::jint id){if(auto owner=self.lock())owner->processWindowEvent(::jxx::NEW<::jxx::awt::event::WindowEvent>(owner,id));});}
#define ADD_REMOVE(NAME,MEMBER,TYPE) void Window::add##NAME(const ::jxx::Ptr<::jxx::awt::event::TYPE>& l){if(l&&std::find(MEMBER.begin(),MEMBER.end(),l)==MEMBER.end())MEMBER.push_back(l);}void Window::remove##NAME(const ::jxx::Ptr<::jxx::awt::event::TYPE>& l){MEMBER.erase(std::remove(MEMBER.begin(),MEMBER.end(),l),MEMBER.end());}
ADD_REMOVE(WindowListener,windowListeners_,WindowListener) ADD_REMOVE(WindowFocusListener,windowFocusListeners_,WindowFocusListener) ADD_REMOVE(WindowStateListener,windowStateListeners_,WindowStateListener)
#undef ADD_REMOVE
void Window::processWindowEvent(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& e){if(!e)return;const auto id=e->getID();if(id==205)active_=true;else if(id==206)active_=false;else if(id==202){active_=false;displayable_=false;Component::setVisible(false);}for(const auto& l:windowListeners_){if(!l)continue;switch(id){case 200:l->windowOpened(e);break;case 201:l->windowClosing(e);break;case 202:l->windowClosed(e);break;case 203:l->windowIconified(e);break;case 204:l->windowDeiconified(e);break;case 205:l->windowActivated(e);break;case 206:l->windowDeactivated(e);break;}}for(const auto& l:windowFocusListeners_)if(l){if(id==207)l->windowGainedFocus(e);else if(id==208)l->windowLostFocus(e);}if(id==209)for(const auto& l:windowStateListeners_)if(l)l->windowStateChanged(e);}
void Window::setVisible(::jxx::lang::jbool v){if(v)ensureNativeWindow();Component::setVisible(v);if(nativeWindow_){if(v){nativeWindow_->setBounds(getX(),getY(),getWidth(),getHeight());nativeWindow_->show();displayable_=true;}else nativeWindow_->hide();}}void Window::setBounds(const ::jxx::Ptr<Rectangle>& r){if(r)setBounds(r->x,r->y,r->width,r->height);}void Window::setBounds(::jxx::lang::jint x,::jxx::lang::jint y,::jxx::lang::jint w,::jxx::lang::jint h){Component::setBounds(x,y,w,h);if(nativeWindow_)nativeWindow_->setBounds(x,y,w,h);}void Window::pack(){validate();ensureNativeWindow();displayable_=nativeWindow_!=nullptr;}void Window::dispose(){if(nativeWindow_){nativeWindow_->setEventCallback({});nativeWindow_->destroy();nativeWindow_.reset();}active_=false;displayable_=false;Component::setVisible(false);}void Window::toFront(){ensureNativeWindow();if(nativeWindow_)nativeWindow_->toFront();}void Window::toBack(){if(nativeWindow_)nativeWindow_->toBack();}::jxx::lang::jbool Window::isActive()const{return active_;}::jxx::lang::jbool Window::isDisplayable()const{return displayable_;}}
