#include "awt/jxx.awt.AWTEventMulticaster.h"

namespace jxx::awt
{
    namespace
    {
        class AWTEventMulticasterNode final : public AWTEventMulticaster
        {
        public:
            AWTEventMulticasterNode(
                const ::jxx::Ptr<::jxx::util::EventListener>& first,
                const ::jxx::Ptr<::jxx::util::EventListener>& second)
                : AWTEventMulticaster(first, second)
            {
            }
        };
    }
    AWTEventMulticaster::AWTEventMulticaster(const ::jxx::Ptr<::jxx::util::EventListener>& first, const ::jxx::Ptr<::jxx::util::EventListener>& second) : a(first), b(second) {}
    ::jxx::Ptr<::jxx::util::EventListener> AWTEventMulticaster::addInternal(const ::jxx::Ptr<::jxx::util::EventListener>& first,const ::jxx::Ptr<::jxx::util::EventListener>& second){if(!first)return second;if(!second)return first;return ::jxx::NEW<AWTEventMulticasterNode>(first, second);} 
    ::jxx::Ptr<::jxx::util::EventListener> AWTEventMulticaster::removeInternal(const ::jxx::Ptr<::jxx::util::EventListener>& listener,const ::jxx::Ptr<::jxx::util::EventListener>& oldListener){if(!listener||listener==oldListener)return nullptr;auto multicaster=::jxx::CAST<AWTEventMulticaster>(listener);return multicaster?multicaster->remove(oldListener):listener;}
    ::jxx::Ptr<::jxx::util::EventListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::util::EventListener>& oldListener){if(oldListener==a)return b;if(oldListener==b)return a;auto nextA=removeInternal(a,oldListener);auto nextB=removeInternal(b,oldListener);if(nextA==a&&nextB==b)return ::jxx::CAST<::jxx::util::EventListener>(thisPtr());return addInternal(nextA,nextB);}
    ::jxx::Ptr<::jxx::awt::event::ActionListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::ActionListener>& first,const ::jxx::Ptr<::jxx::awt::event::ActionListener>& second){return ::jxx::CAST<::jxx::awt::event::ActionListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::ActionListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::ActionListener>& listener,const ::jxx::Ptr<::jxx::awt::event::ActionListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::ActionListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::AdjustmentListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::AdjustmentListener>& first,const ::jxx::Ptr<::jxx::awt::event::AdjustmentListener>& second){return ::jxx::CAST<::jxx::awt::event::AdjustmentListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::AdjustmentListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::AdjustmentListener>& listener,const ::jxx::Ptr<::jxx::awt::event::AdjustmentListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::AdjustmentListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::ComponentListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::ComponentListener>& first,const ::jxx::Ptr<::jxx::awt::event::ComponentListener>& second){return ::jxx::CAST<::jxx::awt::event::ComponentListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::ComponentListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::ComponentListener>& listener,const ::jxx::Ptr<::jxx::awt::event::ComponentListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::ComponentListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::ContainerListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::ContainerListener>& first,const ::jxx::Ptr<::jxx::awt::event::ContainerListener>& second){return ::jxx::CAST<::jxx::awt::event::ContainerListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::ContainerListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::ContainerListener>& listener,const ::jxx::Ptr<::jxx::awt::event::ContainerListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::ContainerListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::FocusListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::FocusListener>& first,const ::jxx::Ptr<::jxx::awt::event::FocusListener>& second){return ::jxx::CAST<::jxx::awt::event::FocusListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::FocusListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::FocusListener>& listener,const ::jxx::Ptr<::jxx::awt::event::FocusListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::FocusListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener>& first,const ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener>& second){return ::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener>& listener,const ::jxx::Ptr<::jxx::awt::event::HierarchyBoundsListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::HierarchyListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::HierarchyListener>& first,const ::jxx::Ptr<::jxx::awt::event::HierarchyListener>& second){return ::jxx::CAST<::jxx::awt::event::HierarchyListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::HierarchyListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::HierarchyListener>& listener,const ::jxx::Ptr<::jxx::awt::event::HierarchyListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::HierarchyListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::InputMethodListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::InputMethodListener>& first,const ::jxx::Ptr<::jxx::awt::event::InputMethodListener>& second){return ::jxx::CAST<::jxx::awt::event::InputMethodListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::InputMethodListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::InputMethodListener>& listener,const ::jxx::Ptr<::jxx::awt::event::InputMethodListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::InputMethodListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::ItemListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::ItemListener>& first,const ::jxx::Ptr<::jxx::awt::event::ItemListener>& second){return ::jxx::CAST<::jxx::awt::event::ItemListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::ItemListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::ItemListener>& listener,const ::jxx::Ptr<::jxx::awt::event::ItemListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::ItemListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::KeyListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::KeyListener>& first,const ::jxx::Ptr<::jxx::awt::event::KeyListener>& second){return ::jxx::CAST<::jxx::awt::event::KeyListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::KeyListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::KeyListener>& listener,const ::jxx::Ptr<::jxx::awt::event::KeyListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::KeyListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::MouseListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::MouseListener>& first,const ::jxx::Ptr<::jxx::awt::event::MouseListener>& second){return ::jxx::CAST<::jxx::awt::event::MouseListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::MouseListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::MouseListener>& listener,const ::jxx::Ptr<::jxx::awt::event::MouseListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::MouseListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::MouseMotionListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::MouseMotionListener>& first,const ::jxx::Ptr<::jxx::awt::event::MouseMotionListener>& second){return ::jxx::CAST<::jxx::awt::event::MouseMotionListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::MouseMotionListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::MouseMotionListener>& listener,const ::jxx::Ptr<::jxx::awt::event::MouseMotionListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::MouseMotionListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::MouseWheelListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::MouseWheelListener>& first,const ::jxx::Ptr<::jxx::awt::event::MouseWheelListener>& second){return ::jxx::CAST<::jxx::awt::event::MouseWheelListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::MouseWheelListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::MouseWheelListener>& listener,const ::jxx::Ptr<::jxx::awt::event::MouseWheelListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::MouseWheelListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::TextListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::TextListener>& first,const ::jxx::Ptr<::jxx::awt::event::TextListener>& second){return ::jxx::CAST<::jxx::awt::event::TextListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::TextListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::TextListener>& listener,const ::jxx::Ptr<::jxx::awt::event::TextListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::TextListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::WindowFocusListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::WindowFocusListener>& first,const ::jxx::Ptr<::jxx::awt::event::WindowFocusListener>& second){return ::jxx::CAST<::jxx::awt::event::WindowFocusListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::WindowFocusListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::WindowFocusListener>& listener,const ::jxx::Ptr<::jxx::awt::event::WindowFocusListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::WindowFocusListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::WindowListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::WindowListener>& first,const ::jxx::Ptr<::jxx::awt::event::WindowListener>& second){return ::jxx::CAST<::jxx::awt::event::WindowListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::WindowListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::WindowListener>& listener,const ::jxx::Ptr<::jxx::awt::event::WindowListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::WindowListener>(removeInternal(listener,oldListener));}
    ::jxx::Ptr<::jxx::awt::event::WindowStateListener> AWTEventMulticaster::add(const ::jxx::Ptr<::jxx::awt::event::WindowStateListener>& first,const ::jxx::Ptr<::jxx::awt::event::WindowStateListener>& second){return ::jxx::CAST<::jxx::awt::event::WindowStateListener>(addInternal(first,second));}
    ::jxx::Ptr<::jxx::awt::event::WindowStateListener> AWTEventMulticaster::remove(const ::jxx::Ptr<::jxx::awt::event::WindowStateListener>& listener,const ::jxx::Ptr<::jxx::awt::event::WindowStateListener>& oldListener){return ::jxx::CAST<::jxx::awt::event::WindowStateListener>(removeInternal(listener,oldListener));}
    void AWTEventMulticaster::actionPerformed(const ::jxx::Ptr<::jxx::awt::event::ActionEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ActionListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ActionListener>(b);if(first)first->actionPerformed(event);if(second)second->actionPerformed(event);}
    void AWTEventMulticaster::adjustmentValueChanged(const ::jxx::Ptr<::jxx::awt::event::AdjustmentEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::AdjustmentListener>(a);auto second=::jxx::CAST<::jxx::awt::event::AdjustmentListener>(b);if(first)first->adjustmentValueChanged(event);if(second)second->adjustmentValueChanged(event);}
    void AWTEventMulticaster::componentResized(const ::jxx::Ptr<::jxx::awt::event::ComponentEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ComponentListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ComponentListener>(b);if(first)first->componentResized(event);if(second)second->componentResized(event);}
    void AWTEventMulticaster::componentMoved(const ::jxx::Ptr<::jxx::awt::event::ComponentEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ComponentListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ComponentListener>(b);if(first)first->componentMoved(event);if(second)second->componentMoved(event);}
    void AWTEventMulticaster::componentShown(const ::jxx::Ptr<::jxx::awt::event::ComponentEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ComponentListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ComponentListener>(b);if(first)first->componentShown(event);if(second)second->componentShown(event);}
    void AWTEventMulticaster::componentHidden(const ::jxx::Ptr<::jxx::awt::event::ComponentEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ComponentListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ComponentListener>(b);if(first)first->componentHidden(event);if(second)second->componentHidden(event);}
    void AWTEventMulticaster::componentAdded(const ::jxx::Ptr<::jxx::awt::event::ContainerEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ContainerListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ContainerListener>(b);if(first)first->componentAdded(event);if(second)second->componentAdded(event);}
    void AWTEventMulticaster::componentRemoved(const ::jxx::Ptr<::jxx::awt::event::ContainerEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ContainerListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ContainerListener>(b);if(first)first->componentRemoved(event);if(second)second->componentRemoved(event);}
    void AWTEventMulticaster::focusGained(const ::jxx::Ptr<::jxx::awt::event::FocusEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::FocusListener>(a);auto second=::jxx::CAST<::jxx::awt::event::FocusListener>(b);if(first)first->focusGained(event);if(second)second->focusGained(event);}
    void AWTEventMulticaster::focusLost(const ::jxx::Ptr<::jxx::awt::event::FocusEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::FocusListener>(a);auto second=::jxx::CAST<::jxx::awt::event::FocusListener>(b);if(first)first->focusLost(event);if(second)second->focusLost(event);}
    void AWTEventMulticaster::ancestorMoved(const ::jxx::Ptr<::jxx::awt::event::HierarchyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(a);auto second=::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(b);if(first)first->ancestorMoved(event);if(second)second->ancestorMoved(event);}
    void AWTEventMulticaster::ancestorResized(const ::jxx::Ptr<::jxx::awt::event::HierarchyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(a);auto second=::jxx::CAST<::jxx::awt::event::HierarchyBoundsListener>(b);if(first)first->ancestorResized(event);if(second)second->ancestorResized(event);}
    void AWTEventMulticaster::hierarchyChanged(const ::jxx::Ptr<::jxx::awt::event::HierarchyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::HierarchyListener>(a);auto second=::jxx::CAST<::jxx::awt::event::HierarchyListener>(b);if(first)first->hierarchyChanged(event);if(second)second->hierarchyChanged(event);}
    void AWTEventMulticaster::inputMethodTextChanged(const ::jxx::Ptr<::jxx::awt::event::InputMethodEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::InputMethodListener>(a);auto second=::jxx::CAST<::jxx::awt::event::InputMethodListener>(b);if(first)first->inputMethodTextChanged(event);if(second)second->inputMethodTextChanged(event);}
    void AWTEventMulticaster::caretPositionChanged(const ::jxx::Ptr<::jxx::awt::event::InputMethodEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::InputMethodListener>(a);auto second=::jxx::CAST<::jxx::awt::event::InputMethodListener>(b);if(first)first->caretPositionChanged(event);if(second)second->caretPositionChanged(event);}
    void AWTEventMulticaster::itemStateChanged(const ::jxx::Ptr<::jxx::awt::event::ItemEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::ItemListener>(a);auto second=::jxx::CAST<::jxx::awt::event::ItemListener>(b);if(first)first->itemStateChanged(event);if(second)second->itemStateChanged(event);}
    void AWTEventMulticaster::keyTyped(const ::jxx::Ptr<::jxx::awt::event::KeyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::KeyListener>(a);auto second=::jxx::CAST<::jxx::awt::event::KeyListener>(b);if(first)first->keyTyped(event);if(second)second->keyTyped(event);}
    void AWTEventMulticaster::keyPressed(const ::jxx::Ptr<::jxx::awt::event::KeyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::KeyListener>(a);auto second=::jxx::CAST<::jxx::awt::event::KeyListener>(b);if(first)first->keyPressed(event);if(second)second->keyPressed(event);}
    void AWTEventMulticaster::keyReleased(const ::jxx::Ptr<::jxx::awt::event::KeyEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::KeyListener>(a);auto second=::jxx::CAST<::jxx::awt::event::KeyListener>(b);if(first)first->keyReleased(event);if(second)second->keyReleased(event);}
    void AWTEventMulticaster::mouseClicked(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseListener>(b);if(first)first->mouseClicked(event);if(second)second->mouseClicked(event);}
    void AWTEventMulticaster::mousePressed(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseListener>(b);if(first)first->mousePressed(event);if(second)second->mousePressed(event);}
    void AWTEventMulticaster::mouseReleased(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseListener>(b);if(first)first->mouseReleased(event);if(second)second->mouseReleased(event);}
    void AWTEventMulticaster::mouseEntered(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseListener>(b);if(first)first->mouseEntered(event);if(second)second->mouseEntered(event);}
    void AWTEventMulticaster::mouseExited(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseListener>(b);if(first)first->mouseExited(event);if(second)second->mouseExited(event);}
    void AWTEventMulticaster::mouseDragged(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseMotionListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseMotionListener>(b);if(first)first->mouseDragged(event);if(second)second->mouseDragged(event);}
    void AWTEventMulticaster::mouseMoved(const ::jxx::Ptr<::jxx::awt::event::MouseEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseMotionListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseMotionListener>(b);if(first)first->mouseMoved(event);if(second)second->mouseMoved(event);}
    void AWTEventMulticaster::mouseWheelMoved(const ::jxx::Ptr<::jxx::awt::event::MouseWheelEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::MouseWheelListener>(a);auto second=::jxx::CAST<::jxx::awt::event::MouseWheelListener>(b);if(first)first->mouseWheelMoved(event);if(second)second->mouseWheelMoved(event);}
    void AWTEventMulticaster::textValueChanged(const ::jxx::Ptr<::jxx::awt::event::TextEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::TextListener>(a);auto second=::jxx::CAST<::jxx::awt::event::TextListener>(b);if(first)first->textValueChanged(event);if(second)second->textValueChanged(event);}
    void AWTEventMulticaster::windowGainedFocus(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowFocusListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowFocusListener>(b);if(first)first->windowGainedFocus(event);if(second)second->windowGainedFocus(event);}
    void AWTEventMulticaster::windowLostFocus(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowFocusListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowFocusListener>(b);if(first)first->windowLostFocus(event);if(second)second->windowLostFocus(event);}
    void AWTEventMulticaster::windowOpened(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowOpened(event);if(second)second->windowOpened(event);}
    void AWTEventMulticaster::windowClosing(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowClosing(event);if(second)second->windowClosing(event);}
    void AWTEventMulticaster::windowClosed(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowClosed(event);if(second)second->windowClosed(event);}
    void AWTEventMulticaster::windowIconified(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowIconified(event);if(second)second->windowIconified(event);}
    void AWTEventMulticaster::windowDeiconified(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowDeiconified(event);if(second)second->windowDeiconified(event);}
    void AWTEventMulticaster::windowActivated(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowActivated(event);if(second)second->windowActivated(event);}
    void AWTEventMulticaster::windowDeactivated(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowListener>(b);if(first)first->windowDeactivated(event);if(second)second->windowDeactivated(event);}
    void AWTEventMulticaster::windowStateChanged(const ::jxx::Ptr<::jxx::awt::event::WindowEvent>& event){auto first=::jxx::CAST<::jxx::awt::event::WindowStateListener>(a);auto second=::jxx::CAST<::jxx::awt::event::WindowStateListener>(b);if(first)first->windowStateChanged(event);if(second)second->windowStateChanged(event);}
}
